package book1createstreams.p02fromFunctions.iterate;

import java.util.stream.Stream;

public class Example1 {
	  public static void main(String[] args) {
		    Stream<Long> stream = Stream.iterate(2L, n  ->  n * n)
		            .limit(6);

		    stream.forEach(System.out::println);
	  }
}
//iterate() method creates a sequential ordered stream.

//The iterate() method takes two arguments: a seed and a function.
//
//A seed is the first element of the stream. The second element is 
//generated by applying the function to the first element. 
//The third element is generated by applying the function on the second element.
//
//Therefore the elements are: seed, f(seed), f(f(seed)), f(f(f(seed)))....